server:
  port: 8888


jasypt:
  encryptor:
    password: G0CvDz7oJn6


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: ENC(i8QgEN4uOy2E1rHzrpSTYA==)
    password: ENC(i8QgEN4uOy2E1rHzrpSTYA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
